cabal-version: 1.24
name:          reflex-dom-test-selenium
version:       0.0.0.1
license:       BSD3
license-file:  LICENSE
maintainer:    ryan.trinkle@gmail.com
author:        Ryan Trinkle
stability:     Experimental
synopsis:      Testing framework for selenium tests
category:
    FRP, Web, GUI, HTML, Javascript, Reactive, Reactivity, User Interfaces, User-interface

build-type:    Simple

library
    exposed-modules:  Reflex.Dom.Test.Selenium
    hs-source-dirs:   src
    default-language: Haskell98
    ghc-options:
        -Wall -fwarn-tabs -funbox-strict-fields -O2 -ferror-spans
        -fspecialise-aggressively

    build-depends:
        async,
        base >= 4.7 && < 4.23,
        bytestring >= 0.10 && < 0.13,
        chrome-test-utils,
        exceptions,
        hspec-core < 2.12,
        hspec-webdriver >= 1.2.2,
        http-types,
        jsaddle >= 0.9.0.0 && < 0.10,
        jsaddle-warp,
        network,
        process,
        reflex-dom-core,
        silently,
        text >= 1.2 && < 2.2,
        wai,
        warp,
        webdriver < 0.13,
        websockets

    if (!os(linux) || !arch(x86_64))
        buildable: False
