name: github-action

on: [push, pull_request] 

jobs:
  build:
    strategy:
      matrix:
        ghc: ['8.4.4', '8.6.5', '8.8.4', '8.10.7', '9.2.5', '9.4.3']
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}

    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
    - uses: pierotofy/set-swap-space@v1.0
      with:
        swap-size-gb: 10
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: obsidiansystems/jsaddle
        ref: aa/ghc94
        path: jsaddle
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-build-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}

    - name: Set up cabal project file to avoid webkit2gtk
      run: cp cabal.project-nogtk cabal.project
    - name: Install dependencies
      run: cabal build --only-dependencies --enable-tests --enable-benchmarks all
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
